### PR TITLE
Replace bech32 and old chacha with noble and scure packages

### PR DESCRIPTION
**Pull request by paulmillr**
#280 improved dependency situation a lot.

- `bech32` was replaced with audited `@scure/base`
- `@stablelib` was replaced with `@noble/ciphers`

cc @ukstv

### CODE REVIEW

**Comment by ukstv** [comment]
Amazing!!

**Comment by ukstv** [comment]
CC @oed

**Review by mirceanis — CHANGES_REQUESTED** [review]
Thanks for contributing this, and for all your other work too!
Code looks good, you'll need to update `yarn.lock` to make the CI checks pass.
BTW, do you plan an audit for `@noble/ciphers` too?

**Comment by paulmillr** [comment]
yeah

**Pull request merged**
